//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryReal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

   /* public partial class Product_view
    {
        public Nullable<double> Price { get; set; }
        public Nullable<double> Mass { get; set; }
        public string Material_name { get; set; }
        [Key]
        public string Name { get; set; }
        public string Type_name { get; set; }
    }*/
}
