//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryReal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        public Nullable<System.DateTime> Sale_date { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Number_of_regular_customers_card { get; set; }
        public double Sale_price { get; set; }
        [Key]
        public int SaleID { get; set; }
    
        public virtual Client Clients { get; set; }
        public virtual Product Products { get; set; }
    }
}
